program: train_sequence.py
name: train_sequence_hyper
method: bayes
metric:
  name: valid_loss
  goal: minimize
parameters:
  learning_rate:
    min: 0.00001
    max: 0.01
  batch_size: 
    values: [256,512,1024]
  epochs: 
    values: [1,2,3]
  optimizer:
    values: ["adam", "sgd"]