wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1748138529
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 13
      - 14
      - 23
      - 37
      4: 3.10.13
      5: 0.19.11
      8:
      - 2
      - 5
      13: linux-x86_64
batch_size:
  desc: null
  value: 256
epochs:
  desc: null
  value: 3
learning_rate:
  desc: null
  value: 0.004152081328177904
optimizer:
  desc: null
  value: sgd
